// <auto-generated />
using System;
using DataAccesLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccesLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210911060519_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DataAccesLayer.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstVariant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FourthVariant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QuestionText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RightAnswer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondVariant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThirdVariant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3ff65e4-49bd-4b7d-bfe5-448add9d5b33"),
                            FirstVariant = "Humanity",
                            FourthVariant = "Household",
                            QuestionText = "In the UK, the abbreviation NHS stands for National what Service?",
                            RightAnswer = "Health",
                            SecondVariant = "Health",
                            ThirdVariant = "Honour"
                        },
                        new
                        {
                            Id = new Guid("dfff40e2-823c-41d1-82a8-92866beb6b3e"),
                            FirstVariant = "Pocahontas",
                            FourthVariant = "Elsa",
                            QuestionText = "Which Disney character famously leaves a glass slipper behind at a royal ball?",
                            RightAnswer = "Cinderella",
                            SecondVariant = "Sleeping Beauty",
                            ThirdVariant = "Cinderella"
                        },
                        new
                        {
                            Id = new Guid("c248f691-14d0-4903-b0de-680f935a5786"),
                            FirstVariant = "Hangar",
                            FourthVariant = "Carousel",
                            QuestionText = "What name is given to the revolving belt machinery in an airport that delivers checked luggage from the plane to baggage reclaim?",
                            RightAnswer = "Carousel",
                            SecondVariant = "Terminal",
                            ThirdVariant = "Concourse"
                        },
                        new
                        {
                            Id = new Guid("fa994cdd-d023-46d2-bfa9-f03f51ab3ddc"),
                            FirstVariant = "Phillips",
                            FourthVariant = "Ronseal",
                            QuestionText = "Which of these brands was chiefly associated with the manufacture of household locks?",
                            RightAnswer = "Chubb",
                            SecondVariant = "Flymo",
                            ThirdVariant = "Chubb"
                        },
                        new
                        {
                            Id = new Guid("146d12b7-f4b1-46d1-b76f-35d911e425e1"),
                            FirstVariant = "Republicanism",
                            FourthVariant = "Liberalism",
                            QuestionText = "The hammer and sickle is one of the most recognisable symbols of which political ideology?",
                            RightAnswer = "Communism",
                            SecondVariant = "Communism",
                            ThirdVariant = "Conservatism"
                        },
                        new
                        {
                            Id = new Guid("5f27960d-282e-4c92-8975-b685b1ca5191"),
                            FirstVariant = "Bratz Dolls",
                            FourthVariant = "Transformers",
                            QuestionText = "Which toys have been marketed with the phrase “robots in disguise”?",
                            RightAnswer = "Transformers",
                            SecondVariant = "Sylvanian Families",
                            ThirdVariant = "Hatchimals"
                        },
                        new
                        {
                            Id = new Guid("43465c18-8e29-40c2-8369-e24b6590b002"),
                            FirstVariant = "Angry",
                            FourthVariant = "Shy",
                            QuestionText = "What does the word loquacious mean?",
                            RightAnswer = "Chatty",
                            SecondVariant = "Chatty",
                            ThirdVariant = "Beautiful"
                        },
                        new
                        {
                            Id = new Guid("4f45024b-45bd-48bf-a943-ae431bb38d2c"),
                            FirstVariant = "Childbirth",
                            FourthVariant = "Old age",
                            QuestionText = "Obstetrics is a branch of medicine particularly concerned with what?",
                            RightAnswer = "Childbirth",
                            SecondVariant = "Broken bones",
                            ThirdVariant = "Heart conditions"
                        },
                        new
                        {
                            Id = new Guid("1f0fa010-fee2-4dcc-a1c8-e64ded001485"),
                            FirstVariant = "Bow-tie, braces and tweed jacket",
                            FourthVariant = "Cape, velvet jacket and frilly shirt",
                            QuestionText = "In Doctor Who, what was the signature look of the fourth Doctor, as portrayed by Tom Baker?",
                            RightAnswer = "Wide-brimmed hat and extra long scarf",
                            SecondVariant = "Wide-brimmed hat and extra long scarf",
                            ThirdVariant = "Pinstripe suit and trainers"
                        },
                        new
                        {
                            Id = new Guid("10be75e0-90c9-4d2f-8cc9-d0548fa7a9dd"),
                            FirstVariant = "Ramadan",
                            FourthVariant = "Hanukkah",
                            QuestionText = "Which of these religious observances lasts for the shortest period of time during the calendar year?",
                            RightAnswer = "Diwali",
                            SecondVariant = "Diwali",
                            ThirdVariant = "Lent"
                        },
                        new
                        {
                            Id = new Guid("341ad7a0-cfd2-4004-a42b-b1e785ab2830"),
                            FirstVariant = "Bahamas",
                            FourthVariant = "Bermuda",
                            QuestionText = "At the closest point, which island group is only 50 miles south-east of the coast of Florida?",
                            RightAnswer = "Bahamas",
                            SecondVariant = "US Virgin Islands",
                            ThirdVariant = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = new Guid("5bc53373-f15c-4cc7-8491-5b0f50faf502"),
                            FirstVariant = "Empire State Building",
                            FourthVariant = "Big Ben Clock Tower",
                            QuestionText = " Construction of which of these famous landmarks was completed first?",
                            RightAnswer = "Big Ben Clock Tower",
                            SecondVariant = "Royal Albert Hall",
                            ThirdVariant = "Eiffel Tower"
                        },
                        new
                        {
                            Id = new Guid("4276dce0-dc74-49e1-9f60-87172952c0d7"),
                            FirstVariant = "Gray whale",
                            FourthVariant = "Humpback whale",
                            QuestionText = "Which of these cetaceans is classified as a “toothed whale”?",
                            RightAnswer = "Sperm whale",
                            SecondVariant = "Minke whale",
                            ThirdVariant = "Sperm whale"
                        },
                        new
                        {
                            Id = new Guid("6ac3f615-295b-4903-90f6-3338b52b6db1"),
                            FirstVariant = "David Lloyd George",
                            FourthVariant = "John Major",
                            QuestionText = "Who is the only British politician to have held all four “Great Offices of State” at some point during their career?",
                            RightAnswer = "James Callaghan",
                            SecondVariant = "Harold Wilson",
                            ThirdVariant = "James Callaghan"
                        },
                        new
                        {
                            Id = new Guid("51b51dd3-bad6-43aa-95a8-9c967f163b10"),
                            FirstVariant = "Calico Jack",
                            FourthVariant = "Captain Kidd",
                            QuestionText = "In 1718, which pirate died in battle off the coast of what is now North Carolina?",
                            RightAnswer = "Blackbeard",
                            SecondVariant = "Blackbeard",
                            ThirdVariant = "Bartholomew Roberts"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
